package rahulstech.swing.calculator.view;

import com.sun.tools.javac.Main;
import rahulstech.swing.calculator.history.HistoryEntry;
import rahulstech.swing.calculator.history.HistoryStorage;
import rahulstech.swing.calculator.parser.Calculator;
import rahulstech.swing.calculator.parser.CalculatorException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.math.BigDecimal;

/**
 * @author Rahul Bagchi
 */
public class CalculatorWindow extends javax.swing.JFrame {

    private Calculator calculator;
    private boolean showingPlaceholder = true;

    /**
     * Creates new form CalculatorWindow
     */
    public CalculatorWindow() {
        initComponents();
        this.calculator = new Calculator();
        onPostInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expressionInput = new javax.swing.JTextField();
        result = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnPercentance = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMultiplication = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPeriod = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnAnswer = new javax.swing.JButton();
        btnAverage = new javax.swing.JButton();
        btnRemainder = new javax.swing.JButton();
        btnComma = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        expressionInput.setFont(expressionInput.getFont().deriveFont((float)18));
        expressionInput.setText("0");

        result.setFont(result.getFont().deriveFont((result.getFont().getStyle() | java.awt.Font.ITALIC), 14));

        btnPanel.setPreferredSize(new java.awt.Dimension(100, 40));

        btnClear.setFont(btnClear.getFont().deriveFont(btnClear.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnClear.setText("C");
        btnClear.setPreferredSize(new java.awt.Dimension(60, 40));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnOpen.setFont(btnOpen.getFont().deriveFont(btnOpen.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnOpen.setText("(");
        btnOpen.setPreferredSize(new java.awt.Dimension(60, 40));
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnClose.setFont(btnClose.getFont().deriveFont(btnClose.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnClose.setText(")");
        btnClose.setPreferredSize(new java.awt.Dimension(60, 40));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnPercentance.setFont(btnPercentance.getFont().deriveFont(btnPercentance.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnPercentance.setText("%");
        btnPercentance.setPreferredSize(new java.awt.Dimension(60, 40));
        btnPercentance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn7.setFont(btn7.getFont().deriveFont(btn7.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn7.setText("7");
        btn7.setPreferredSize(new java.awt.Dimension(115, 40));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn8.setFont(btn8.getFont().deriveFont(btn8.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn8.setText("8");
        btn8.setPreferredSize(new java.awt.Dimension(115, 40));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn9.setFont(btn9.getFont().deriveFont(btn9.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn9.setText("9");
        btn9.setPreferredSize(new java.awt.Dimension(115, 40));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnDivision.setFont(btnDivision.getFont().deriveFont(btnDivision.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnDivision.setText("/");
        btnDivision.setPreferredSize(new java.awt.Dimension(60, 40));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn4.setFont(btn4.getFont().deriveFont(btn4.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn4.setText("4");
        btn4.setPreferredSize(new java.awt.Dimension(115, 40));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnMinus.setFont(btnMinus.getFont().deriveFont(btnMinus.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnMinus.setText("-");
        btnMinus.setPreferredSize(new java.awt.Dimension(60, 40));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnMultiplication.setFont(btnMultiplication.getFont().deriveFont(btnMultiplication.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnMultiplication.setText("*");
        btnMultiplication.setPreferredSize(new java.awt.Dimension(60, 40));
        btnMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn5.setFont(btn5.getFont().deriveFont(btn5.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn5.setText("5");
        btn5.setPreferredSize(new java.awt.Dimension(115, 40));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn1.setFont(btn1.getFont().deriveFont(btn1.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn1.setText("1");
        btn1.setPreferredSize(new java.awt.Dimension(115, 40));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn2.setFont(btn2.getFont().deriveFont(btn2.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn2.setText("2");
        btn2.setPreferredSize(new java.awt.Dimension(115, 40));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn3.setFont(btn3.getFont().deriveFont(btn3.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn3.setText("3");
        btn3.setPreferredSize(new java.awt.Dimension(115, 40));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn6.setFont(btn6.getFont().deriveFont(btn6.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn6.setText("6");
        btn6.setPreferredSize(new java.awt.Dimension(115, 40));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btn0.setFont(btn0.getFont().deriveFont(btn0.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btn0.setText("0");
        btn0.setPreferredSize(new java.awt.Dimension(115, 40));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnPeriod.setFont(btnPeriod.getFont().deriveFont(btnPeriod.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btnPeriod.setText(".");
        btnPeriod.setPreferredSize(new java.awt.Dimension(115, 40));
        btnPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnEqual.setFont(btnEqual.getFont().deriveFont(btnEqual.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btnEqual.setText("=");
        btnEqual.setPreferredSize(new java.awt.Dimension(115, 40));
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnPlus.setFont(btnPlus.getFont().deriveFont(btnPlus.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnPlus.setText("+");
        btnPlus.setPreferredSize(new java.awt.Dimension(60, 40));
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnBackspace.setFont(btnBackspace.getFont().deriveFont(btnBackspace.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnBackspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rahulstech/swing/calculator/view/backspace-solid.png"))); // NOI18N
        btnBackspace.setPreferredSize(new java.awt.Dimension(60, 40));
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnPower.setFont(btnPower.getFont().deriveFont(btnPower.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnPower.setText("^y");
        btnPower.setPreferredSize(new java.awt.Dimension(60, 40));
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnSquare.setFont(btnSquare.getFont().deriveFont(btnSquare.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnSquare.setText("^2");
        btnSquare.setPreferredSize(new java.awt.Dimension(65, 40));
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnSqrt.setFont(btnSqrt.getFont().deriveFont(btnSqrt.getFont().getStyle() | java.awt.Font.BOLD, 12));
        btnSqrt.setText("SQRT");
        btnSqrt.setPreferredSize(new java.awt.Dimension(50, 40));
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnAnswer.setFont(btnAnswer.getFont().deriveFont(btnAnswer.getFont().getStyle() | java.awt.Font.BOLD, 12));
        btnAnswer.setText("ANS");
        btnAnswer.setPreferredSize(new java.awt.Dimension(60, 40));
        btnAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnAverage.setFont(btnAverage.getFont().deriveFont(btnAverage.getFont().getStyle() | java.awt.Font.BOLD, 10));
        btnAverage.setText("AVG");
        btnAverage.setPreferredSize(new java.awt.Dimension(40, 40));
        btnAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnRemainder.setFont(btnRemainder.getFont().deriveFont(btnRemainder.getFont().getStyle() | java.awt.Font.BOLD, 10));
        btnRemainder.setText("REMAINDER");
        btnRemainder.setPreferredSize(new java.awt.Dimension(60, 40));
        btnRemainder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        btnComma.setFont(btnComma.getFont().deriveFont(btnComma.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btnComma.setText(",");
        btnComma.setPreferredSize(new java.awt.Dimension(65, 40));
        btnComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBtn(evt);
            }
        });

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(btnPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemainder, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComma, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnPanelLayout.createSequentialGroup()
                        .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPanelLayout.createSequentialGroup()
                                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelLayout.createSequentialGroup()
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelLayout.createSequentialGroup()
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelLayout.createSequentialGroup()
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelLayout.createSequentialGroup()
                                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPercentance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultiplication, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnAverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemainder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPercentance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rahulstech/swing/calculator/view/history-solid.png"))); // NOI18N
        btnHistory.setToolTipText("show history");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickHistory(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expressionInput)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHistory)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHistory)
                .addGap(18, 18, 18)
                .addComponent(expressionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onPostInit() {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                HistoryStorage.saveHistory();
            }
        });
        expressionInput.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) { e.consume(); }

            @Override
            public void keyPressed(KeyEvent e) { e.consume(); }

            @Override
            public void keyReleased(KeyEvent e) { e.consume(); }
        });
        HistoryStorage.loadHistory();
        Font font = loadFont(Font.TRUETYPE_FONT,"LcdSolid-VPzB.ttf");
        if (null != font) {
            expressionInput.setFont(font.deriveFont(18f));
        }
    }

    private void onClickBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickBtn
        final Object which = evt.getSource();
        if (btn0 == which) {
            appendText("0");
        }
        else if (btnPeriod == which) {
            appendText(".");
        }
        else if (btnPlus == which) {
            appendText("+");
        }
        else if (btn1 == which) {
            appendText("1");
        }
        else if (btn2 == which) {
            appendText("2");
        }
        else if (btn3 == which) {
            appendText("3");
        }
        else if (btnMinus == which) {
            appendText("-");
        }
        else if (btn4 == which) {
            appendText("4");
        }
        else if (btn5 == which) {
            appendText("5");
        }
        else if (btn6 == which) {
            appendText("6");
        }
        else if (btnDivision == which) {
            appendText("/");
        }
        else if (btn7 == which) {
            appendText("7");
        }
        else if (btn8 == which) {
            appendText("8");
        }
        else if (btn9 == which) {
            appendText("9");
        }
        else if (btnMultiplication == which) {
            appendText("*");
        }
        else if (btnOpen == which) {
            appendText("(");
        }
        else if (btnClose == which) {
            appendText(")");
        }
        else if (btnPercentance == which) {
            appendText("%");
        }
        else if (btnAnswer == which) {
            appendText("ANS");
        }
        else if (btnAverage == which) {
            appendText("AVG(");
        }
        else if (btnSqrt == which) {
            appendText("SQRT(");
        }
        else if (btnSquare == which) {
            appendText("^2");
        }
        else if (btnPower == which) {
            appendText("^");
        }
        else if (btnRemainder == which) {
            appendText("REMAINDER(");
        }
        else if (btnComma == which) {
            appendText(",");
        }
        else if (btnClear == which) {
            clear();
        }
        else if (btnEqual == which) {
            calculate();
        }
        else if (btnBackspace == which) {
            backspace();
        }
    }//GEN-LAST:event_onClickBtn

    private void onClickHistory(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickHistory
        HistoryWindow historyWindow = new HistoryWindow();
        historyWindow.setOnChooseHistoryEntryListener(entry -> onChooseFromHistory(entry));
        historyWindow.setVisible(true);
    }//GEN-LAST:event_onClickHistory

    private void appendText(String text) {
        if (showingPlaceholder) {
            expressionInput.setText(null);
        }
        int selectionStart = expressionInput.getSelectionStart();
        int selectionEnd = expressionInput.getSelectionEnd();
        int sectionLength = selectionEnd-selectionStart;
        int cursorPosition = expressionInput.getCaretPosition();
        String expression = expressionInput.getText();
        StringBuilder builder = new StringBuilder(expression);
        if (sectionLength > 0) {
            builder.replace(selectionStart,selectionEnd,text);
        }
        else {
            builder.insert(cursorPosition,text);
        }
        expressionInput.setText(builder.toString());
        showingPlaceholder = false;
    }

    private void clear() {
        expressionInput.setText("0");
        result.setText(null);
        showingPlaceholder = true;
    }

    private void backspace() {
        if (showingPlaceholder) {
            return;
        }
        int selectionStart = expressionInput.getSelectionStart();
        int selectionEnd = expressionInput.getSelectionEnd();
        int sectionLength = selectionEnd-selectionStart;
        int cursorPosition = expressionInput.getCaretPosition();
        String expression = expressionInput.getText();
        StringBuilder builder = new StringBuilder(expression);
        if (sectionLength > 0) {
            builder.replace(selectionStart,selectionEnd,"");
        }
        else if (cursorPosition > 0) {
            builder.deleteCharAt(cursorPosition-1);
        }
        expressionInput.setText(builder.toString());
        showingPlaceholder = false;
    }

    private void calculate() {
        String expression = expressionInput.getText();
        if (null == expression || "".equals(expression)) return;
        try {
            BigDecimal value = calculator.calculate(expression);
            result.setText(value.toString());

            HistoryEntry entry = new HistoryEntry();
            entry.setExpression(expression);
            entry.setResult(value);
            HistoryStorage.addToHistory(entry);
        }
        catch (CalculatorException e) {
            JOptionPane.showMessageDialog(this,e.getMessage(),
                    "Error in Calculation",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onChooseFromHistory(HistoryEntry entry) {
        clear();
        appendText(entry.getExpression());
        result.setText(entry.getResult().toString());
    }

    public static Font loadFont(int format, String file) {
        try {
            InputStream in = ClassLoader.getSystemResourceAsStream(file);
            Font font = Font.createFont(format,in);
            return font;
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public static void main(String args[]) {
        Font font = loadFont(Font.TRUETYPE_FONT,"DancingScript-Bold.ttf");
        if (null != font) {
            UIManager.put("Button.font",font.deriveFont(Font.BOLD,24));
        }
        new CalculatorWindow().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAnswer;
    private javax.swing.JButton btnAverage;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnComma;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiplication;
    private javax.swing.JButton btnOpen;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnPercentance;
    private javax.swing.JButton btnPeriod;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnRemainder;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSquare;
    private javax.swing.JTextField expressionInput;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables
}
